disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
opt_in_rules: # some rules are only opt-in
  # Find all the available rules by running: swiftlint rules
  - trailing_semicolon
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
included: # paths to include during linting. `--path` is ignored if present.
  - sampleLint
